### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Civilian-No-001** [cvzi/darkmodewallpaper#17]
Android 11
Unknown reason

It is captured after unlocking and entering the home screen, the home screen wallpaper has not changed, and the lock screen wallpaper is reset after the screen is turned off and can be automatic restored

> FATAL EXCEPTION: main
Process: com.github.cvzi.darkmodewallpaper, PID: 25277
java.lang.IllegalArgumentException: Receiver not registered: com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$OnUnLockBroadcastReceiver@af3af56
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1440)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1642)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$OnUnLockBroadcastReceiver.unregister(DarkWallpaperService.kt:328)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.unRegisterOnUnLock(DarkWallpaperService.kt:348)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.access$unRegisterOnUnLock(DarkWallpaperService.kt:219)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$onLockScreenStatusChanged$1.invoke(DarkWallpaperService.kt:364)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$onLockScreenStatusChanged$1.invoke(DarkWallpaperService.kt:354)
	at com.github.cvzi.darkmodewallpaper.StaticDayAndNightProvider.get(ImageProvider.kt:209)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.onLockScreenStatusChanged(DarkWallpaperService.kt:354)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.onVisibilityChanged(DarkWallpaperService.kt:400)
	at android.service.wallpaper.WallpaperService$Engine.reportVisibility(WallpaperService.java:1190)
	at android.service.wallpaper.WallpaperService$Engine.doVisibilityChanged(WallpaperService.java:1170)
	at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1500)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:44)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by cvzi** [comment]
Thanks for the log

**Comment by Civilian-No-001** [comment]
This app crashes when the wallpaper is replaced with another app


> FATAL EXCEPTION: main

Process: com.github.cvzi.darkmodewallpaper, PID: 15328
java.lang.RuntimeException: Unable to stop service com.github.cvzi.darkmodewallpaper.DarkWallpaperService@820882c: java.lang.IllegalArgumentException: Receiver not registered: com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$OnUnLockBroadcastReceiver@d5f92f5
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4380)
	at android.app.ActivityThread.access$1900(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1961)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$OnUnLockBroadcastReceiver@d5f92f5
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1440)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1642)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:715)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine$OnUnLockBroadcastReceiver.unregister(DarkWallpaperService.kt:328)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.unRegisterOnUnLock(DarkWallpaperService.kt:348)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService$WallpaperEngine.onDestroy(DarkWallpaperService.kt:299)
	at android.service.wallpaper.WallpaperService$Engine.detach(WallpaperService.java:1295)
	at android.service.wallpaper.WallpaperService.onDestroy(WallpaperService.java:1587)
	at com.github.cvzi.darkmodewallpaper.DarkWallpaperService.onDestroy(DarkWallpaperService.kt:166)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4360)
	... 8 more
